# Generated by Django 2.1.5 on 2020-01-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=3000, max_digits=10000)),
                ('summary', models.TextField(blank=True, null=True)),
                ('feature', models.BooleanField(default=True)),
            ],
        ),
    ]
