# Generated by Django 2.1.5 on 2020-01-14 23:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200115_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 14, 23, 26, 35, 262267, tzinfo=utc), null=True),
        ),
    ]
